﻿﻿6:18:40.281 PM
 Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:389): Could not instantiate robot jdk.internal.util.Preconditions! ERROR  1  Could not instantiate robot jdk.internal.util.Preconditions!  edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:389)      See https://wpilib.org/stacktrace for more information.    The above stacktrace can help determine where the error occurred.  Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:383): The robot program quit unexpectedly. This is usually due to a code error. ERROR  1  The robot program quit unexpectedly. This is usually due to a code error.
  The above stacktrace can help determine where the error occurred.
  See https://wpilib.org/stacktrace for more information.
  edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:383)    	at frc.robot.Main.main(Main.java:13)  	at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:510)  	at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:370)  	at frc.robot.Robot.<init>(Robot.java:59)  	at frc.robot.RobotContainer.<init>(RobotContainer.java:61)  	at frc.robot.subsystems.LimelightAligner.<init>(LimelightAligner.java:29)  	at java.base/java.util.ArrayList.get(Unknown Source)  	at java.base/java.util.Objects.checkIndex(Unknown Source)  	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)  	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)  	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)  Error at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source): Unhandled exception instantiating robot jdk.internal.util.Preconditions java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4 ERROR  1  Unhandled exception instantiating robot jdk.internal.util.Preconditions java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4  java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source) 
